seed: 42
model_dir: ../../models/cycle-vc
resume_checkpoint: false

train:
  fp16: false
  batch_size: 64
  num_epochs: 12500
  save_interval: 100
  lambda_cycle: 10
  lambda_id: 5

data:
  n_mel: 80

  x_dir: ../../dataset/vc/gan/msk/wav
  y_dir: ../../dataset/vc/gan/jsut/wav

  x_stats: ../../dataset/vc/gan/msk/mel_stats/stats.pt
  y_stats: ../../dataset/vc/gan/jsut/mel_stats/stats.pt

  segment_length: 128

  x_train_length: 500
  y_train_length: 500

model:

  generator:
    base_channels: 128
    n_residuals: 6

  discriminator:
    base_channels: 64
    spectral_norm: true

optimizer:
  lr: 1.0
  betas: [0.5, 0.99]
